apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-set-tracker-deployment
  labels:
    app: api-set-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-set-tracker
  template:
    metadata:
      labels:
        app: api-set-tracker
    spec:
      containers:
        - name: api-set-tracker
          image: api-set-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Colombo"
          volumeMounts:
            - name: log-volume
              mountPath: /logs
      volumes:
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: api-set-tracker-service
spec:
  selector:
    app: api-set-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
